server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        # Public routes to app-management-service
        - id: app-management-service-unprotected-route
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/app-management/**

        # Public routes to auth-service
        - id: auth-unprotected-routes
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/login,/api/v1/auth/create,/api/v1/auth/forgot-password/**,/api/v1/auth/verify-password-reset-token,/api/v1/auth/change-password

        # Public routes to user-service
        - id: user-service-unprotected-route
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/users/register,/api/v1/users/verify

        # Secured routes to auth-service, account-service, user-service, app-management-service
        # through the Resource-server
        - id: resource-server
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**,/api/v1/accounts/**

